# Generated by Django 5.0.6 on 2024-06-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_profile_uang_alter_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uang',
            new_name='money',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
