# Generated by Django 5.0.6 on 2024-06-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_profile_uang_alter_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uang',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
