# Generated by Django 5.0.6 on 2024-06-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_alter_profile_uang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uang',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
