# Generated by Django 5.0.6 on 2024-06-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.TextField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.TextField(blank=True, max_length=12),
        ),
    ]
