# Generated by Django 5.0.6 on 2024-06-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_profile_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_completed',
        ),
    ]
