# Generated by Django 5.0.6 on 2024-06-22 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_umkm_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umkm',
            old_name='user',
            new_name='owner',
        ),
    ]
