# Generated by Django 5.0.6 on 2024-06-23 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_alter_umkm_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umkm',
            name='owner',
        ),
    ]
