# Generated by Django 5.0.6 on 2024-06-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0030_remove_umkm_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='EWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wallet_number', models.CharField(max_length=100)),
                ('wallet_type', models.CharField(choices=[('ShopeePay', 'ShopeePay'), ('Dana', 'Dana'), ('OVO', 'OVO'), ('Gopay', 'Gopay')], max_length=20)),
            ],
        ),
    ]
