# Generated by Django 5.0.6 on 2024-06-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0033_withdraw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Withdraw',
        ),
    ]
