# Generated by Django 5.0.6 on 2024-06-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0035_withdraw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UMKM',
        ),
    ]
