# Generated by Django 5.0.6 on 2024-06-23 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0037_umkm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EWallet',
        ),
    ]
