# Generated by Django 5.0.6 on 2024-06-23 23:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0039_ewallets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_purcashed', models.PositiveIntegerField(null=True)),
                ('total_investment', models.DecimalField(decimal_places=2, max_digits=22)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('total_payment', models.IntegerField(null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('umkm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.umkm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
