# Generated by Django 5.0.6 on 2024-06-24 04:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0041_topup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='money',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
